__default__:
  name: YOUR_NAME
  account: YOUR_ACCOUNT
  time: "12:00:00"
  partition: YOUR_PARTITION
  nodes: 1
  ntasks: 8

train_retip:
  partition: YOUR_PARTITION
  nodes: 1
  ntasks: 8

retip:
  partition: YOUR_PARTITION
  nodes: 1
  ntasks: 8