# Specify desired tools here
tools: ["deepccs", "graffms", "sigmaccs", "darkchem", "c3sdb", "rtp"]

# Repository Paths
rtp_path: RTP_REPOSITORY_PATH
deepccs_path: DEEPCCS_REPOSITORY_PATH
sigmaccs_path: SIGMACCS_REPOSITORY_PATH
darkchem_path: DARKCHEM_MODELS_PATH
c3sdb_path: C3SDB_REPOSITORY_PATH

# HPC envmodules
# NOTE: use "" if no relevant module
envmodule:
  gcc: GCC_MODULE
  cuda: CUDA_MODULE

# Database Chunking
db:
  filename: test_batch_size-316
  chunk_size: 25

# Adducts to predict for all tools (minus CFM-ID)
adducts: ["[M+H]+", "[M-H]-"]

# CFM-ID Adducts
# NOTE: Web server has many available adducts; CLI/docker only 2
cfmid_adducts: ["[M+H]+", "[M-H]-"]

# Singularity Parameters (for CFM-ID)
singularity-args: "--bind /PATH/TO/INPUT_DATA:$HOME"
use-singularity: TRUE

# GrAFF-MS Parameters
collision_energy: [10.0, 20.0, 40.0]
graffms:
  repo_path: GRAFFMS_REPOSITORY_PATH
  input_path: 
  output_path:
  batch_size: 512
  gpus: 0  # 1
  precision: 32
  num_workers: 8
  instrument: Thermo Finnigan Elite Orbitrap
  has_isotopes: 0
  min_probability: 1.e-4
  min_mz: 50
  subsample: 0
  seed: 0
  ignore_errors: 1

# RTP Parameters
fp_size: 2048
rtp_model_path: PATH_TO_RTP_MODEL.pkl
